# Sample configuration for IPTV_Indexer
scraper:
  urls:
    - https://securestreaming.example.com/iptv-list
    - https://iptv-demo.example.net/channels
  output:
    format: m3u
    file: playlist.m3u
  credentials:
    - site: securestreaming.example.com
      loginUrl: https://securestreaming.example.com/api/login
      username: demoUser
      password: demoPass123
    - site: iptv-demo.example.net
      loginUrl: https://iptv-demo.example.net/api/auth
      username: sampleUser
      password: samplePass456

nordvpn:
  useProxy: true
  proxy:
    protocol: http
    host: us1234.nordvpn.com
    port: 89
    username: YOUR_NORDVPN_USERNAME
    password: YOUR_NORDVPN_PASSWORD
  useCli: true
  cliServer: us
  cliTimeoutMs: 60000
